# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h1A3gepZn9k4z9ebyHsj8wQz2Ily06ud

Atividade Aula 2
"""

print("Ciências da Computação – Cruzeiro do Sul")

profissão = input("Qual a sua profissão? ")
print("Sua profissão é", profissão)

idade = input("Qual a sua idade? ")

print("Sua idade é", idade)

#ou desta outra forma mais completa

idade = input("Qual é a sua idade? ")
if idade.isnumeric():
    print(idade + " anos")
else:
    print(idade)

sobrenome = input("Qual é seu ultimo sobrenome? ")
print("Família", sobrenome)

esporte = input("Qual seu esporte favorito? ")
print(esporte, "é o esporte que você mais gosta!")