# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awqAVP210SR0HKpc_1A8SVl1FWmgRjZ8
"""

#Atividade ↓

#1

for par in range(0, 101, 2):
  print(par, end=" ")

#2

for num1 in range(1, 51):
    print(num1, end=" ")

for num2 in range(52, 101, 2):
    print(num2, end=" ")
  
#3

n = int(input("Digite um valor inteiro e positivo: "))
soma = 0

for i in range(1, n+1):
    soma += 1/i
    
print("A soma é:", soma)

#4

n = int(input("Quantos valores deseja digitar? "))

valores = []

for i in range(n):
    valor = float(input("Digite um valor real: "))
    valores.append(valor)

pos = 0
neg = 0
menor = valores[0]

for valor in valores:
    if valor > 0:
        pos += 1
    elif valor < 0:
        neg += 1
    if valor < menor:
        menor = valor

print("Valores positivos:", pos)
print("Valores negativos:", neg)
print("Menor valor:", menor)

#5

n = int(input("Quantas pessoas deseja digitar? "))
altura_m = []
altura_h = []
soma_m = 0
soma_h = 0
qtd_m = 0
qtd_h = 0

for i in range(n):
    sexo = input("Digite o sexo (M/F) da pessoa {}: ".format(i+1))
    altura = float(input("Digite a altura da pessoa {} em metros: ".format(i+1)))
    if sexo.upper() == "M":
        altura_h.append(altura)
        soma_h += altura
        qtd_h += 1
    elif sexo.upper() == "F":
        altura_m.append(altura)
        soma_m += altura
        qtd_m += 1
    else:
        print("Sexo inválido. Digite M para masculino ou F para feminino.")

if qtd_m > 0:
    media_m = soma_m / qtd_m
    print("Altura média das mulheres: {:.2f} metros".format(media_m))
else:
    print("Não foram digitadas alturas de mulheres.")

if qtd_h > 0:
    media_h = soma_h / qtd_h
    print("Altura média dos homens: {:.2f} metros".format(media_h))
else:
    print("Não foram digitadas alturas de homens.")