# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awqAVP210SR0HKpc_1A8SVl1FWmgRjZ8

Perímetro e Área
"""

base = float(input("Qual o tamnho da base do retângulo: "))
altura = float(input("Qual a altura do retângulo: "))

p = 2 * (base + altura)
area = (base * altura)

print("O perímetro do retângulo é", p)
print("A Área do retângulo é", area)

"""Salário acrescido com 5% de comissão"""

salario = float(input("Qual o seu salário atual: R$"))

comissao = salario * 1.05

print("O salário com comissão é de: R$", comissao)

"""Velocidade Média"""

distancia = float(input("Digite a distância entre as cidades (em km): "))
tempo = float(input("Digite o tempo de viagem (em horas): "))

VM = distancia / tempo

print("A velocidade média é de", VM, "km/h")

a = float(input("Qual é o valor do coeficiente A: "))
b = float(input("Qual é o valor do coeficiente B: "))
c = float(input("Qual é o valor do coeficiente C: "))

delta = b**2 - 4 * a * c

raizx = (-b + delta ** 0.5) / (2 * a)
raizy = (-b - delta ** 0.5) / (2 * a)

print(f'Os valores das raízes são raiz_x {raizx} e raix_y {raizy}')

"""Cotação Dólar para Real"""

cotacao = float(input("Qual a cotação do dólar atual: "))
dolares = float(input("Digite a quantidade em dólares a serem convertidas: "))

reais = dolares * cotacao

print("O valor equivalente em reais é: R$", reais)

"""Valor pago no Restaurante ComaBem"""

gasto = float(input("Digite o valor gasto no restaurante ComaBem: R$"))

taxa = gasto * 0.1
pago = gasto + taxa

print("O valor a ser pago no restaurante ComaBem é de R$", pago)

"""Temperatura"""

tc = float(input("Digite temperatura em Celsius: "))

tf = 1.8 * tc + 32
tk = tc + 273

print("A temperatura", tc,"°C em Fahrenheit é de", tf, "°F")
print("A temperatura", tc,"°C em Kelvin é de", tk, "K")