# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awqAVP210SR0HKpc_1A8SVl1FWmgRjZ8
"""

#Atividade ↓

#Atividade - 1

#Número de 0 a 9


n = float(input("Digite um número: "))

if n >= 0 and n <= 9:
  print("Valor correto")

else:
  print("Valor incorreto")


#2
#Salário por turnos

turno = input("Digite o turno de trabalho (N - Noturno ou D - Diurno): ")
horas = float(input("Digite a quantidade de horas trabalhadas: "))

valor_hora = 0

if turno == 'N':
  valor_hora = 45.0
else:
  valor_hora = 37.5

salario = valor_hora * horas

print("O valor do salário é R$ {:.2f}".format(salario))


#3
#Desconto em compras

compras = float(input("Digite o valor das compras: "))

desconto = 0

if compras >= 200:
  valor_desconto = compras * 0.8
  print("O valor da compra com desconto é R$ {:.2f}".format(valor_desconto))
else:
    print("O valor da compra é R$ {:.2f}".format(compras))


#4
#Contas a pagar

luz = float(input("Digite o valor da conta de luz: "))
agua = float(input("Digite o valor da conta de água: "))
telefone = float(input("Digite o valor da conta de telefone: "))
salario = float(input("Digite o valor do seu salário: "))

total = luz + agua + telefone

if salario >= total:
  restante = salario - total
  print("O valor que restou do salário após pagar as contas é R$ {:.2f}".format(restante))
else:
  print("Salário insuficiente!")