# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awqAVP210SR0HKpc_1A8SVl1FWmgRjZ8
"""

#Atividade ↓

#Atividade - 1

import math

idade = int(input("Digite a sua idade: "))

  if idade < 16:
    print("Você não é eleitor.")
  elif idade >= 18 and idade <= 65:
    print("Você é eleitor obrigatório.")
  else:
    print("Você é eleitor facultativo.")

#2

a = int(input("Digite o valor de a: "))
b = int(input("Digite o valor de b: "))
c = int(input("Digite o valor de c: "))

  if a == 0:
    print("Não é equação do segundo grau")
  else:
    delta = b**2 - 4*a*c
  if delta < 0:
    print("Não há raízes reais")
  elif delta == 0:
    raiz = -b / (2*a)
    print("Raiz única", raiz)
  else:
    raiz1 = (-b + math.sqrt(delta)) / (2*a)
    raiz2 = (-b - math.sqrt(delta)) / (2*a)
    print(f"Raízes: {raiz1:.2f} e {raiz2:.2f}")

#3

produto = input("Digite o nome do produto: ")
valor = float(input("Digite o valor da compra: "))

  if valor < 10:
    lucro = 0.7
  elif valor < 30:
    lucro = 0.5
  elif valor < 50:
    lucro = 0.4
  else:
    lucro = 0.3

venda = valor * (1 + lucro)

  print ("Produto: {}".format(produto))
  print("Valor de venda: R$ {:.2f}".format(venda))


#4

n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))
operacao = input("Digite a operação desejada (+, -, *, /): ")
    
  if operacao == "+":
    resultado = n1 + n2
  elif operacao == "-":
    resultado = n1 - n2
  elif operacao == "*":
    resultado = n1 * n2
  elif operacao == "/":
    resultado = n1 / n2
  else:
    print("Operação inválida!")
    resultado = None

  if resultado is not None:
    print("Resultado: {:.2f}".format(resultado))