# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awqAVP210SR0HKpc_1A8SVl1FWmgRjZ8
"""

#Atividade ↓

import math

#1

h = float(input('Digite a altura do tronco da pirâmide: '))
Bmenor = float(input('Digite o tamanho da base menor da pirâmide: '))
Bmaior = float(input('Digite o tamanho da base maior da pirâmide: '))

volume = (h / 3) * (Bmaior ** 2 + Bmenor ** 2 + Bmenor * Bmaior)

print('O volume do tronco da pirâmide será de: {:.2f}'.format(volume),'cm³')

#2

horas = float(input('Digite o valor em horas: '))

print('Você terá {:.0f}'.format (horas * 60),'minutos')

#3

anos = int(input("Digite sua idade em anos: "))
meses = int(input("Digite o número de meses adicionais: "))
dias = int(input("Digite o número de dias adicionais: "))

idade_dias = anos * 365 + meses * 30 + dias

print('A idade em dias é:', idade_dias, 'dias')

#4

prestacao = float(input('Digite o valor da prestação: '))
multa = int(input('Digite a porcentagem da multa: '))
dias = int(input('Digite a quantidade de dias de atraso: '))

total = prestacao + (prestacao * (multa / 100) * dias)

print("O valor da prestação atualizado é: R$ {:.2f}".format(total))

#5

graus = float(input("Digite o valor do ângulo em graus: "))

radianos = math.radians(graus)

seno = math.sin(radianos)

print('Seno:', math.sin(radianos))
print('Cosseno:', math.cos(radianos))
print('Tangente:', math.tan(radianos))